### ISSUE TITLE
Lazy Vim - hello

### ISSUE THREAD

**Issue by sethhorsley** [dpetka2001/dotfiles#2]
Hey I didn't see an easy way to contact you so I'm just making an issue here 😄 
Anyway I've seen you on the LazyVim repo quite a bit and I'm going to Thesoloniki on Tuesday and was wondering if you had sometime next week to grab dinner or lunch. Really appreciate your work on LazyVim!

telegram: `@isthi`
email: `github.dvxhi@sl.isethi.com`

**Comment by dpetka2001** [comment]
Sorry, but I don't live in Thessaloniki. It's just my hometown and haven't updated Github info. Hope you enjoy your stay :)
